AllCops:
  Exclude:
    - 'pkg/**/*'
    - 'spec/fixtures/**/*'
    - 'vendor/bundle/**/*'

Layout/LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false